// <auto-generated />
using System;
using AuthWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthWebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180927104012_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("AuthWebApi.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = "7fed7f3c-d1a2-43b5-bb35-990245d8769d", AccessFailedCount = 0, ConcurrencyStamp = "ef3d598f-2032-47ed-a430-a47497d19dab", EmailConfirmed = false, LockoutEnabled = false, PasswordHash = "5E884898DA28047151D0E56F8DC6292773603D0D6AABBDD62A11EF721D1542D8", PhoneNumberConfirmed = false, TwoFactorEnabled = false, UserName = "test" },
                        new { Id = "4b2bf01b-6a5a-4dcb-9bba-2cd0b400b627", AccessFailedCount = 0, ConcurrencyStamp = "12a1ef69-4d1c-4f43-b147-de2ea0f6ee1a", EmailConfirmed = false, LockoutEnabled = false, PasswordHash = "5E884898DA28047151D0E56F8DC6292773603D0D6AABBDD62A11EF721D1542D8", PhoneNumberConfirmed = false, TwoFactorEnabled = false, UserName = "test2" }
                    );
                });

            modelBuilder.Entity("AuthWebApi.Data.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new { Id = 1, RoleId = "15b1e47f-205c-412f-b882-6a6f5dde39ba", UserId = "7fed7f3c-d1a2-43b5-bb35-990245d8769d" },
                        new { Id = 2, RoleId = "bff9ba43-66fc-4699-9f83-bc189e40fe0c", UserId = "7fed7f3c-d1a2-43b5-bb35-990245d8769d" },
                        new { Id = 3, RoleId = "bff9ba43-66fc-4699-9f83-bc189e40fe0c", UserId = "4b2bf01b-6a5a-4dcb-9bba-2cd0b400b627" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = "15b1e47f-205c-412f-b882-6a6f5dde39ba", ConcurrencyStamp = "14e11770-4aca-4a2e-9aa4-43e0d0dc77f1", Name = "admin" },
                        new { Id = "bff9ba43-66fc-4699-9f83-bc189e40fe0c", ConcurrencyStamp = "dd224720-d44f-40ac-bd94-10f8567f5e26", Name = "user" }
                    );
                });

            modelBuilder.Entity("AuthWebApi.Data.UserRole", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("AuthWebApi.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
